---
- hosts: all
  tasks:
      - name: install python docker module
        pip:
            name: docker
      - name: Create a network
        community.docker.docker_network:
            name: aiod
      - name: Clone api server
        git:
            repo: https://github.com/aiondemand/AIOD-rest-api.git
            dest: /home/iarejula/AIOD-rest-api
            version: develop
      - name: Build Docker image
        community.docker.docker_image:
            name: aiod
            build:
                path: /home/iarejula/AIOD-rest-api
            source: build
